version: '3.8'

services:
  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: unless-stopped

  spring-app:
    image: ashtonsw/snippie:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
    restart: unless-stopped

networks:
  default:
    name: snippie_default