## OAuth2
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user